### ISSUE TITLE
🏁 emily is away ↔ v18.6.2

### ISSUE THREAD

**Issue by jurgentreep** [itchio/itch-compatibility-watchlist#127]
:rotating_light: game [emily is away](https://kyleseeley23.itch.io/emilyisaway) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/1cc55bf781ca82753b40afb6ced96d9a).

:running: Never launches on win10 64bit

**Comment by fasterthanlime** [comment]
Are you per chance double clicking the 'Launch' button? The logs show it was 'cancelled', which happens when one clicks 'Force close' (which is what the 'Launch' button turns into).

**Comment by jurgentreep** [comment]
I cancelled it because it kept hanging. Found out it works if I launch from
the folder though. Still takes a while but eventually launches.

Op ma 5 sep. 2016 17:40 schreef Amos Wenger notifications@github.com:

**Comment by fasterthanlime** [comment]
Do you have some antivirus software running? Or even just Windows Defender?

Since the game installs & runs fine (quickly) on my Windows 10 computer, it's possible that, in your case, it was being run in a sandbox first (seeing as it's a fresh .exe file), and that might've explained the extra delay you were seeing.

If you run it again through the app, do you still see the same behavior?

**Comment by jurgentreep** [comment]
It does actually launch eventually. Only windows defender goes totally nuts for a minute and after that everything's fine :)

There's no reports in windows defender of any kind though.

Also tried to exclude the game in windows defender but that doesn't help.

**Comment by fasterthanlime** [comment]
Ah, windows defender is probably not very happy at all about the itch app in general (connecting to the internet then running .exe files). That's going to be an ongoing struggle :( I'll see if I can work with them maybe.

**Comment by fasterthanlime** [comment]
Closing this in favor of https://github.com/itchio/itch/issues/867
