### ISSUE TITLE
🐧 Impoverished Starfighter ↔ v23.6.1

### ISSUE THREAD

**Issue by Madgui** [itchio/itch-compatibility-watchlist#1399]
Hello,

I have a proble with the itch.io / ubuntu version of your game:
'no executable found'

I found some '.lua' script, perhaps I have to install and configure that interpreter ?

Tell me if you want some more intel.

Regards.

:rotating_light: game [Impoverished Starfighter](https://danbo.itch.io/impoverished-starfighter) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/83272bd117987f75662859cb6658eca3).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
The Linux version of this game is distributed as a .love bundle - the app doesn't support that yet, because it involves installing a version of the Love2D runtime first and running the game with it.

The related issue is this one: https://github.com/itchio/itch/issues/808

For now I'd recommend installing love yourself and downloading the .love file directly from the itch.io website. You'll find instructions here: https://love2d.org/wiki/Getting_Started
