### ISSUE TITLE
🏁 Future Love Space Machine : Glimmer Deck ↔ v23.6.1

### ISSUE THREAD

**Issue by 9uugh** [itchio/itch-compatibility-watchlist#1424]
:rotating_light: game [Future Love Space Machine : Glimmer Deck](https://ripenedpeach.itch.io/future-love-space-machine) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/ae71a15bc2da324ba9d06855127a18af).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
It looks like FLSM uses IndigoRose Setup, which although it [does support silent installs](https://www.indigorose.com/webhelp/suf60/Shared/Command_Line_Options/Command_Line_Options.htm#Installer_Options) does not accept a target location when installing.

What does this mean? This installer type won't be supported by the itch.io app ever (because it doesn't qualify for second-class installer support), so I would advise you to reach out to the developer of FLSM and ask them to upload [portable builds](https://itch.io/docs/itch/integrating/platforms/windows.html) instead.
