### ISSUE TITLE
🐧 Sort the Court! ↔ v23.3.1

### ISSUE THREAD

**Issue by mrmeszaros** [itchio/itch-compatibility-watchlist#821]
:rotating_light: game [Sort the Court!](https://graebor.itch.io/sort-the-court) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/6e75fc1e94b96491ec49f519860816a0).

:running: I have a 64 bit Ubuntu 16.04, the game said: "Some required 32-bit libraries are missing: libXcursor.so.1".

**Comment by fasterthanlime** [comment]
Yep, since there's only a 32-bit build of this game, you have to install the missing libraries (for now).

Here's how to find them:

  * Use the `Search the contents of packages` functionality of this page: http://packages.ubuntu.com/
  * For `keyword`, enter the missing library, in this case, `libXcursor.so.1`
  * For `Distribution`, pick the correct one - for you, it's `xenial` (Ubuntu 16.04)
  * This gives you [the results page](http://packages.ubuntu.com/search?searchon=contents&keywords=libXcursor.so.1&mode=exactfilename&suite=xenial&arch=any), which lists the `libxcursor1` package as the only result
  * You should be able to install it with `sudo apt install libxcursor1:i386`

Hope this helps! I hope to provide automatic dependency installation in a later version of the app.
